language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 1

services:
  - mysql

php:
  - 7.0
  - 7.1

env:
  - SYMFONY_ENV=dev

matrix:
  fast_finish: true

before_install:
  - openssl genrsa -out app/var/jwt/private.pem -aes256 -passout pass:thisisfortests 4096
  - openssl rsa -pubout -in app/var/jwt/private.pem -out app/var/jwt/public.pem -passin pass:thisisfortests
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - touch app/config/parameters_dev.yml
  - touch app/config/parameters_test.yml

install:
  - composer install

before_script:
  - php bin/console --version
  - vendor/bin/phpunit --version
  - vendor/bin/phpspec --version
  - php bin/console doctrine:database:create

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpspec run

after_success:
  - php vendor/bin/coveralls -v
