imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    jms_serializer.array_collection_handler.class: App\Serializer\Handler\ArrayCollectionHandler

framework:
    #esi:             ~
    #translator:      { fallbacks: [ '%locale%' ] }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: [ 'twig' ]
    default_locale:  '%locale%'
    trusted_hosts:   ~
    #trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   '%kernel.root_dir%/../var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        types:
            datetime: App\Doctrine\DBAL\Types\UTCDateTimeType
            datetimetz: App\Doctrine\DBAL\Types\UTCDateTimeType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html
doctrine_migrations:
    dir_name: '%kernel.root_dir%/Migrations'
    namespace: App\Migrations
    table_name: migration_versions
    name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

# http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration
jms_serializer:
    metadata:
         auto_detection: true
    handlers:
        datetime:
            default_format: 'Y-m-d\TH:i:sP' # DATE_RFC3339
            default_timezone: 'UTC'

# https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.rst#step-4-configure-the-bundle
# https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/configuration-in-depth.rst
nelmio_api_doc: ~

# https://github.com/nelmio/NelmioCorsBundle#configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        "^/":
            allow_origin: [ '*' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600

# https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
