app:
    resource: '@AppBundle/Controller/'
    type:     annotation

# https://github.com/gesdinet/JWTRefreshTokenBundle#step-3-configure-your-own-routing-to-refresh-token
gesdinet_jwt_refresh_token:
    path:     /auth/refreshToken
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

# https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.rst#step-3-register-the-routes
NelmioApiDocBundle:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix:   /api/doc
