# Form service configurations
#
# This file contains form service specified configurations.
services:
    app.form.console.user_group:
        class: App\Form\Console\UserGroup
        calls:
            - [ setHelperRoles, [ '@app.services.helper.roles' ] ]
        tags:
            - { name: form.type }

    app.form.console.user:
        class: App\Form\Console\User
        calls:
            - [ setUserGroupService, [ '@app.services.rest.user_group' ] ]
        tags:
            - { name: form.type }
